import React, { Component } from 'react'
import './chooseOffice.css'

export default class ChooseOffice extends Component {
  constructor(props){
      super(props)
      this.state={
         chooseActive:'区域写字楼',
         chooseOfficeData:{
             "北京":{
                '区域写字楼':[
                    {
                       id:1,
                       name:'海淀写字楼'
                    },{
                       id:2,
                       name:'朝阳写字楼'
                   },{
                       id:3,
                       name:'东城写字楼'
                   },{
                       id:4,
                       name:'西城写字楼'
                   },{
                       id:5,
                       name:'丰台写字楼'
                   },{
                       id:6,
                       name:'大兴写字楼'
                   },{
                       id:7,
                       name:'石景山写字楼'
                   },{
                       id:8,
                       name:'昌平写字楼'
                   },{
                       id:9,
                       name:'通州写字楼'
                   },{
                       id:10,
                       name:'顺义写字楼'
                   }
                ],
                '商圈写字楼':[
                   {
                      id:11,
                      name:'科技园区/总部基地写字楼'
                   },{
                      id:12,
                      name:'丽泽桥写字楼'
                  },{
                      id:13,
                      name:'西客站写字楼'
                  },{
                      id:14,
                      name:'六里桥写字楼'
                  },{
                      id:15,
                      name:'方庄写字楼'
                  },{
                      id:16,
                      name:'刘家窑写字楼'
                  },{
                      id:17,
                      name:'宋家庄写字楼'
                  },{
                      id:18,
                      name:'马家堡写字楼'
                  },{
                      id:19,
                      name:'玉泉营写字楼'
                  },{
                      id:20,
                      name:'三元桥写字楼'
                   },{
                       id:21,
                       name:'CBD/国贸写字楼'
                   },{
                       id:22,
                       name:'慈云寺/四惠写字楼'
                   },{
                       id:23,
                       name:'百子湾写字楼'
                   },{
                       id:24,
                       name:'大望路写字楼'
                   },{
                       id:25,
                       name:'双井/劲松写字楼'
                   },{
                       id:26,
                       name:'潘家园/十里河写字楼'
                   },{
                       id:27,
                       name:'安贞写字楼'
                   },{
                       id:28,
                       name:'三里屯写字楼'
                   },{
                       id:29,
                       name:'燕莎写字楼'
                   },{
                       id:30,
                       name:'酒仙桥写字楼'
                   },{
                       id:31,
                       name:'望京写字楼'
                    },{
                       id:32,
                       name:'朝青板块写字楼'
                   },{
                       id:33,
                       name:'常营写字楼'
                   },{
                       id:34,
                       name:'北苑写字楼'
                   },{
                       id:35,
                       name:'高碑店产业园写字楼'
                   },{
                       id:36,
                       name:'双桥写字楼'
                   },{
                       id:37,
                       name:'亚运村写字楼'
                   },{
                       id:38,
                       name:'来广营写字楼'
                   },{
                       id:39,
                       name:'太阳宫写字楼'
                   },{
                       id:40,
                       name:'酒仙桥写字楼'
                   }
               ]
            },
            '上海':{
                '区域写字楼':[
                    {
                        id:31,
                        name:'浦东写字楼'
                    },{
                        id:32,
                        name:'黄浦写字楼'
                    },{
                        id:33,
                        name:'徐汇写字楼'
                    },{
                        id:34,
                        name:'长宁写字楼'
                    },{
                        id:35,
                        name:'静安写字楼'
                    },{
                        id:36,
                        name:'普陀写字楼'
                    },{
                        id:35,
                        name:'闸北写字楼'
                    },{
                        id:36,
                        name:'虹口写字楼'
                    }
                ],
                '商圈写字楼':[
                    {
                        id:41,
                        name:'七宝写字楼'
                    }
                ]
            },
            '天津':{
                '区域写字楼':[
                    {
                        id:51,
                        name:'天河写子楼'
                    }
                ],
                '商圈写字楼':[
                    {
                        id:61,
                        name:'天河北/体育'
                    }
                ]
            },
            '重庆':{
                '区域写字楼':[
                    {
                        id:71,
                        name:'福田写子楼'
                    }
                ],
                '商圈写字楼':[
                    {
                        id:81,
                        name:'南山科技园写字楼'
                    }
                ]
            },
            '广州':{
                '区域写字楼':[
                    {
                        id:91,
                        name:'广州天河写子楼'
                    }
                ],
                '商圈写字楼':[
                    {
                        id:101,
                        name:'广州北/体育'
                    }
                ]
            },
            '深圳':{
                '区域写字楼':[
                    {
                        id:111,
                        name:'深圳天河写子楼'
                    }
                ],
                '商圈写字楼':[
                    {
                        id:121,
                        name:'深圳北/体育'
                    }
                ]
            },
            '杭州':{
                '区域写字楼':[
                    {
                        id:131,
                        name:'杭州天河写子楼'
                    }
                ],
                '商圈写字楼':[
                    {
                        id:141,
                        name:'杭州北/体育'
                    }
                ]
            },
            '成都':{
                '区域写字楼':[
                    {
                        id:151,
                        name:'成都天河写子楼'
                    }
                ],
                '商圈写字楼':[
                    {
                        id:161,
                        name:'成都北/体育'
                    }
                ]
            },
            '大连':{
                '区域写字楼':[
                    {
                        id:171,
                        name:'大连天河写子楼'
                    }
                ],
                '商圈写字楼':[
                    {
                        id:181,
                        name:'大连北/体育'
                    }
                ]
            },
            '南京':{
                '区域写字楼':[
                    {
                        id:191,
                        name:'南京天河写子楼'
                    }
                ],
                '商圈写字楼':[
                    {
                        id:200,
                        name:'南京北/体育'
                    }
                ]
            },
            '西安':{
                '区域写字楼':[
                    {
                        id:201,
                        name:'西安天河写子楼'
                    }
                ],
                '商圈写字楼':[
                    {
                        id:211,
                        name:'西安北/体育'
                    }
                ]
            },
            '武汉':{
                '区域写字楼':[
                    {
                        id:221,
                        name:'武汉河写子楼'
                    }
                ],
                '商圈写字楼':[
                    {
                        id:231,
                        name:'武汉北/体育'
                    }
                ]
            }   
         },
         chooseOfficeResult:[],
         localcity:''
      }
  }
  toggleCon(vals){
    let {
        chooseOfficeData,
        chooseActive
    } = this.state;
    let newCity = localStorage.getItem('city')
    this.setState({
        chooseActive:vals,
        chooseOfficeResult : chooseOfficeData[newCity][vals]
    })
  }
  componentDidMount(){
      let {
        chooseOfficeData,
        chooseActive,
        localcity
      } = this.state;
      let newCity = localStorage.getItem('city')
      this.setState({
        chooseOfficeResult:chooseOfficeData[chooseActive],
        localcity:newCity
      })
  }
  
  render() {
   
    let {
        chooseOfficeData,
        chooseOfficeResult,
        chooseActive,
        localcity
    } = this.state;
    return (
      <div className="chooseOffice_Wrap">
        <div className="chooseOffice_tit">
            好租网>{localcity}写字楼出租
        </div>
        <div className="toggleOffice">
            <div className="toggleOfficeNav">
                <span className={chooseActive =='区域写字楼'? "active" : ''} onClick={()=>{
                    this.toggleCon('区域写字楼')
                }}>区域写字楼</span>
                <span className={chooseActive =='商圈写字楼'? "active" : ''} onClick={()=>{
                    this.toggleCon('商圈写字楼')
                }}>商圈写字楼</span>
            </div>
            <ul className="toggleOfficeCon">
                {
                    chooseOfficeResult && chooseOfficeResult.map((v,i)=>{
                        return <li key={i}>{v.name}</li>
                    })
                }
            </ul>
        </div>
      </div>
    )
  }
}
